jobs:
  aws-setup:
    runs-on: ubuntu-latest
    steps:
      # Clear any pre-existing AWS credentials
      - name: Clear Existing AWS Credentials
        run: |
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Debug AWS Identity
      - name: Debug AWS Identity
        run: aws sts get-caller-identity


