name: Start EKS Cluster and Scan with Trivy and List the Vul Report Results

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  create-eks-cluster:
    runs-on: ubuntu-latest
    steps:
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Install eksctl
      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      # Create the EKS cluster
      - name: Create EKS Cluster
        run: |
          eksctl create cluster \
            --name my-eks-cluster \
            --region eu-central-1 \
            --nodegroup-name standard-workers \
            --node-type t3.medium \
            --nodes 2 \
            --nodes-min 1 \
            --nodes-max 3 \
            --managed

  deploy-vulnerable-application:
    needs: create-eks-cluster
    runs-on: ubuntu-latest
    steps:
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Deploy Vulnerable Application
      - name: Deploy Vulnerable Application
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx
            labels:
              app: nginx
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:1.16 # Known vulnerable version
                  ports:
                  - containerPort: 80
          EOF

  deploy-trivy-operator:
    needs: deploy-vulnerable-application
    runs-on: ubuntu-latest
    steps:
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Set up Kubeconfig
      - name: Set up Kubeconfig
        run: |
          aws eks --region eu-central-1 update-kubeconfig --name my-eks-cluster

      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Deploy Trivy Operator
      - name: Deploy Trivy Operator
        run: |
          helm repo add aqua https://aquasecurity.github.io/helm-charts/
          helm repo update
          helm install trivy-operator aqua/trivy-operator --namespace trivy-system --create-namespace

  fetch-scan-reports:
    needs: deploy-trivy-operator
    runs-on: ubuntu-latest
    steps:
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Set up Kubeconfig
      - name: Set up Kubeconfig
        run: |
          aws eks --region eu-central-1 update-kubeconfig --name my-eks-cluster

      # Verify Kubernetes Cluster Connection
      - name: Verify Kubernetes Cluster Connection
        run: kubectl get nodes

      # Fetch Vulnerability Reports
      - name: Fetch Vulnerability Reports
        run: |
          kubectl get vulnerabilityreports -A

      # List Vulnerability Reports (Detailed)
      - name: List Vulnerability Reports (Detailed)
        run: |
          echo "Listing Vulnerability Reports with Detailed Output:"
          kubectl get vulnerabilityreports -A -o yaml

      # Save Reports as Artifacts
      - name: Save Reports
        run: |
          kubectl get vulnerabilityreports -A -o json > vulnerability-reports.json
      - name: Upload Vulnerability Report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-reports
          path: vulnerability-reports.json

  destroy-cluster:
    needs: fetch-scan-reports
    runs-on: ubuntu-latest
    steps:
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Install eksctl
      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      # Delete EKS Cluster
      - name: Delete EKS Cluster
        run: |
          eksctl delete cluster --name my-eks-cluster --region eu-central-1
