name: Use Existing EKS Cluster and Scan with Trivy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  deploy-vulnerable-application:
    runs-on: ubuntu-latest
    steps:
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Set up kubectl Kubeconfig
      - name: Set up Kubeconfig
        run: |
          aws eks --region eu-central-1 update-kubeconfig --name my-eks-cluster

      # Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Deploy Vulnerable Application
      - name: Deploy Vulnerable Application
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx
            labels:
              app: nginx
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:1.16 # Known vulnerable version
                  ports:
                  - containerPort: 80
          EOF

  deploy-trivy-operator:
    needs: deploy-vulnerable-application
    runs-on: ubuntu-latest
    steps:
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Set up Kubeconfig
      - name: Set up Kubeconfig
        run: |
          aws eks --region eu-central-1 update-kubeconfig --name my-eks-cluster

      # Verify Kubernetes Cluster Connection
      - name: Verify Kubernetes Cluster Connection
        run: kubectl get nodes

      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent
